name: deploy on digital ocean branch master
on:
  push:
    branches:
      - master
  pull_request_review:
    types: [submitted]
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NestJs App
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm use 20
            cd bolivar-rate-api/
            git pull origin master
            pnpm i
            /root/.local/share/pnpm/pm2 restart bolivar-rate-api
